# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: container.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lights_pb2 as lights__pb2
import sensor_pb2 as sensor__pb2
import setpoint_pb2 as setpoint__pb2
import time_pb2 as time__pb2
import controlstate_pb2 as controlstate__pb2
import hwhealth_pb2 as hwhealth__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='container.proto',
  package='teamspatzenhirn',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63ontainer.proto\x12\x0fteamspatzenhirn\x1a\x0clights.proto\x1a\x0csensor.proto\x1a\x0esetpoint.proto\x1a\ntime.proto\x1a\x12\x63ontrolstate.proto\x1a\x0ehwhealth.proto\"\xb5\x03\n\x15NUCtoIOBoardContainer\x12-\n\ttimeStamp\x18\x01 \x01(\x0b\x32\x1a.teamspatzenhirn.TimeStamp\x12\x43\n\x13singleTrackSetpoint\x18\x02 \x01(\x0b\x32$.teamspatzenhirn.SingleTrackSetpointH\x00\x12\x35\n\x0c\x66ullSetpoint\x18\x03 \x01(\x0b\x32\x1d.teamspatzenhirn.FullSetpointH\x00\x12\x35\n\x0cyeetSetpoint\x18\x07 \x01(\x0b\x32\x1d.teamspatzenhirn.YeetSetpointH\x00\x12\x37\n\rtimeSyncReply\x18\x04 \x01(\x0b\x32\x1e.teamspatzenhirn.TimeSyncReplyH\x00\x12\x39\n\x0eindicatorState\x18\x05 \x01(\x0b\x32\x1f.teamspatzenhirn.IndicatorStateH\x00\x12;\n\x0f\x62rakeLightState\x18\x06 \x01(\x0b\x32 .teamspatzenhirn.BrakeLightStateH\x00\x42\t\n\x07payload\"\xab\x02\n\x15IOBoardtoNUCContainer\x12-\n\ttimeStamp\x18\x01 \x01(\x0b\x32\x1a.teamspatzenhirn.TimeStamp\x12\x35\n\x0csensorUpdate\x18\x02 \x01(\x0b\x32\x1d.teamspatzenhirn.SensorUpdateH\x00\x12;\n\x0ftimeSyncRequest\x18\x03 \x01(\x0b\x32 .teamspatzenhirn.TimeSyncRequestH\x00\x12\x35\n\x0c\x63ontrolState\x18\x04 \x01(\x0e\x32\x1d.teamspatzenhirn.ControlStateH\x00\x12-\n\x08hwHealth\x18\x05 \x01(\x0b\x32\x19.teamspatzenhirn.HwHealthH\x00\x42\t\n\x07payloadb\x06proto3'
  ,
  dependencies=[lights__pb2.DESCRIPTOR,sensor__pb2.DESCRIPTOR,setpoint__pb2.DESCRIPTOR,time__pb2.DESCRIPTOR,controlstate__pb2.DESCRIPTOR,hwhealth__pb2.DESCRIPTOR,])




_NUCTOIOBOARDCONTAINER = _descriptor.Descriptor(
  name='NUCtoIOBoardContainer',
  full_name='teamspatzenhirn.NUCtoIOBoardContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='teamspatzenhirn.NUCtoIOBoardContainer.timeStamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='singleTrackSetpoint', full_name='teamspatzenhirn.NUCtoIOBoardContainer.singleTrackSetpoint', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fullSetpoint', full_name='teamspatzenhirn.NUCtoIOBoardContainer.fullSetpoint', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yeetSetpoint', full_name='teamspatzenhirn.NUCtoIOBoardContainer.yeetSetpoint', index=3,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeSyncReply', full_name='teamspatzenhirn.NUCtoIOBoardContainer.timeSyncReply', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indicatorState', full_name='teamspatzenhirn.NUCtoIOBoardContainer.indicatorState', index=5,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brakeLightState', full_name='teamspatzenhirn.NUCtoIOBoardContainer.brakeLightState', index=6,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='teamspatzenhirn.NUCtoIOBoardContainer.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=129,
  serialized_end=566,
)


_IOBOARDTONUCCONTAINER = _descriptor.Descriptor(
  name='IOBoardtoNUCContainer',
  full_name='teamspatzenhirn.IOBoardtoNUCContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='teamspatzenhirn.IOBoardtoNUCContainer.timeStamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensorUpdate', full_name='teamspatzenhirn.IOBoardtoNUCContainer.sensorUpdate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeSyncRequest', full_name='teamspatzenhirn.IOBoardtoNUCContainer.timeSyncRequest', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='controlState', full_name='teamspatzenhirn.IOBoardtoNUCContainer.controlState', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hwHealth', full_name='teamspatzenhirn.IOBoardtoNUCContainer.hwHealth', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='teamspatzenhirn.IOBoardtoNUCContainer.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=569,
  serialized_end=868,
)

_NUCTOIOBOARDCONTAINER.fields_by_name['timeStamp'].message_type = time__pb2._TIMESTAMP
_NUCTOIOBOARDCONTAINER.fields_by_name['singleTrackSetpoint'].message_type = setpoint__pb2._SINGLETRACKSETPOINT
_NUCTOIOBOARDCONTAINER.fields_by_name['fullSetpoint'].message_type = setpoint__pb2._FULLSETPOINT
_NUCTOIOBOARDCONTAINER.fields_by_name['yeetSetpoint'].message_type = setpoint__pb2._YEETSETPOINT
_NUCTOIOBOARDCONTAINER.fields_by_name['timeSyncReply'].message_type = time__pb2._TIMESYNCREPLY
_NUCTOIOBOARDCONTAINER.fields_by_name['indicatorState'].message_type = lights__pb2._INDICATORSTATE
_NUCTOIOBOARDCONTAINER.fields_by_name['brakeLightState'].message_type = lights__pb2._BRAKELIGHTSTATE
_NUCTOIOBOARDCONTAINER.oneofs_by_name['payload'].fields.append(
  _NUCTOIOBOARDCONTAINER.fields_by_name['singleTrackSetpoint'])
_NUCTOIOBOARDCONTAINER.fields_by_name['singleTrackSetpoint'].containing_oneof = _NUCTOIOBOARDCONTAINER.oneofs_by_name['payload']
_NUCTOIOBOARDCONTAINER.oneofs_by_name['payload'].fields.append(
  _NUCTOIOBOARDCONTAINER.fields_by_name['fullSetpoint'])
_NUCTOIOBOARDCONTAINER.fields_by_name['fullSetpoint'].containing_oneof = _NUCTOIOBOARDCONTAINER.oneofs_by_name['payload']
_NUCTOIOBOARDCONTAINER.oneofs_by_name['payload'].fields.append(
  _NUCTOIOBOARDCONTAINER.fields_by_name['yeetSetpoint'])
_NUCTOIOBOARDCONTAINER.fields_by_name['yeetSetpoint'].containing_oneof = _NUCTOIOBOARDCONTAINER.oneofs_by_name['payload']
_NUCTOIOBOARDCONTAINER.oneofs_by_name['payload'].fields.append(
  _NUCTOIOBOARDCONTAINER.fields_by_name['timeSyncReply'])
_NUCTOIOBOARDCONTAINER.fields_by_name['timeSyncReply'].containing_oneof = _NUCTOIOBOARDCONTAINER.oneofs_by_name['payload']
_NUCTOIOBOARDCONTAINER.oneofs_by_name['payload'].fields.append(
  _NUCTOIOBOARDCONTAINER.fields_by_name['indicatorState'])
_NUCTOIOBOARDCONTAINER.fields_by_name['indicatorState'].containing_oneof = _NUCTOIOBOARDCONTAINER.oneofs_by_name['payload']
_NUCTOIOBOARDCONTAINER.oneofs_by_name['payload'].fields.append(
  _NUCTOIOBOARDCONTAINER.fields_by_name['brakeLightState'])
_NUCTOIOBOARDCONTAINER.fields_by_name['brakeLightState'].containing_oneof = _NUCTOIOBOARDCONTAINER.oneofs_by_name['payload']
_IOBOARDTONUCCONTAINER.fields_by_name['timeStamp'].message_type = time__pb2._TIMESTAMP
_IOBOARDTONUCCONTAINER.fields_by_name['sensorUpdate'].message_type = sensor__pb2._SENSORUPDATE
_IOBOARDTONUCCONTAINER.fields_by_name['timeSyncRequest'].message_type = time__pb2._TIMESYNCREQUEST
_IOBOARDTONUCCONTAINER.fields_by_name['controlState'].enum_type = controlstate__pb2._CONTROLSTATE
_IOBOARDTONUCCONTAINER.fields_by_name['hwHealth'].message_type = hwhealth__pb2._HWHEALTH
_IOBOARDTONUCCONTAINER.oneofs_by_name['payload'].fields.append(
  _IOBOARDTONUCCONTAINER.fields_by_name['sensorUpdate'])
_IOBOARDTONUCCONTAINER.fields_by_name['sensorUpdate'].containing_oneof = _IOBOARDTONUCCONTAINER.oneofs_by_name['payload']
_IOBOARDTONUCCONTAINER.oneofs_by_name['payload'].fields.append(
  _IOBOARDTONUCCONTAINER.fields_by_name['timeSyncRequest'])
_IOBOARDTONUCCONTAINER.fields_by_name['timeSyncRequest'].containing_oneof = _IOBOARDTONUCCONTAINER.oneofs_by_name['payload']
_IOBOARDTONUCCONTAINER.oneofs_by_name['payload'].fields.append(
  _IOBOARDTONUCCONTAINER.fields_by_name['controlState'])
_IOBOARDTONUCCONTAINER.fields_by_name['controlState'].containing_oneof = _IOBOARDTONUCCONTAINER.oneofs_by_name['payload']
_IOBOARDTONUCCONTAINER.oneofs_by_name['payload'].fields.append(
  _IOBOARDTONUCCONTAINER.fields_by_name['hwHealth'])
_IOBOARDTONUCCONTAINER.fields_by_name['hwHealth'].containing_oneof = _IOBOARDTONUCCONTAINER.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['NUCtoIOBoardContainer'] = _NUCTOIOBOARDCONTAINER
DESCRIPTOR.message_types_by_name['IOBoardtoNUCContainer'] = _IOBOARDTONUCCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NUCtoIOBoardContainer = _reflection.GeneratedProtocolMessageType('NUCtoIOBoardContainer', (_message.Message,), {
  'DESCRIPTOR' : _NUCTOIOBOARDCONTAINER,
  '__module__' : 'container_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.NUCtoIOBoardContainer)
  })
_sym_db.RegisterMessage(NUCtoIOBoardContainer)

IOBoardtoNUCContainer = _reflection.GeneratedProtocolMessageType('IOBoardtoNUCContainer', (_message.Message,), {
  'DESCRIPTOR' : _IOBOARDTONUCCONTAINER,
  '__module__' : 'container_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.IOBoardtoNUCContainer)
  })
_sym_db.RegisterMessage(IOBoardtoNUCContainer)


# @@protoc_insertion_point(module_scope)
