# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlstate.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controlstate.proto',
  package='teamspatzenhirn',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63ontrolstate.proto\x12\x0fteamspatzenhirn*B\n\x0c\x43ontrolState\x12\x0b\n\x07TESTING\x10\x00\x12\x07\n\x03\x43UP\x10\x01\x12\x0e\n\nAUTONOMOUS\x10\x02\x12\x0c\n\x08HW_FAULT\x10\x03\x62\x06proto3'
)

_CONTROLSTATE = _descriptor.EnumDescriptor(
  name='ControlState',
  full_name='teamspatzenhirn.ControlState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TESTING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CUP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTONOMOUS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HW_FAULT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=39,
  serialized_end=105,
)
_sym_db.RegisterEnumDescriptor(_CONTROLSTATE)

ControlState = enum_type_wrapper.EnumTypeWrapper(_CONTROLSTATE)
TESTING = 0
CUP = 1
AUTONOMOUS = 2
HW_FAULT = 3


DESCRIPTOR.enum_types_by_name['ControlState'] = _CONTROLSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
