# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hwhealth.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hwhealth.proto',
  package='teamspatzenhirn',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ehwhealth.proto\x12\x0fteamspatzenhirn\"\xfd\x03\n\x08HwHealth\x12\x0f\n\x07\x62\x61ttery\x18\x01 \x01(\x08\x12\x0e\n\x06\x62uzzer\x18\x02 \x01(\x08\x12\x12\n\nled_status\x18\x03 \x01(\x08\x12\x12\n\nled_orange\x18\x04 \x01(\x08\x12\x10\n\x08led_blue\x18\x05 \x01(\x08\x12\x0b\n\x03pwm\x18\x06 \x01(\x08\x12\x17\n\x0findicator_front\x18\x07 \x01(\x08\x12\x16\n\x0eindicator_rear\x18\x08 \x01(\x08\x12\x0b\n\x03usb\x18\t \x01(\x08\x12\x0b\n\x03udp\x18\n \x01(\x08\x12\x10\n\x08protobuf\x18\x0b \x01(\x08\x12\x0c\n\x04sbus\x18\x0c \x01(\x08\x12\x11\n\tsbus_uart\x18\r \x01(\x08\x12\x0b\n\x03\x61\x63\x63\x18\x0e \x01(\x08\x12\x0c\n\x04gyro\x18\x0f \x01(\x08\x12\x10\n\x08steering\x18\x10 \x01(\x08\x12\x1a\n\x12vesc_rx_front_left\x18\x11 \x01(\x08\x12\x1b\n\x13vesc_rx_front_right\x18\x12 \x01(\x08\x12\x19\n\x11vesc_rx_rear_left\x18\x13 \x01(\x08\x12\x1a\n\x12vesc_rx_rear_right\x18\x14 \x01(\x08\x12\x1a\n\x12vesc_tx_front_left\x18\x15 \x01(\x08\x12\x1b\n\x13vesc_tx_front_right\x18\x16 \x01(\x08\x12\x19\n\x11vesc_tx_rear_left\x18\x17 \x01(\x08\x12\x1a\n\x12vesc_tx_rear_right\x18\x18 \x01(\x08\x62\x06proto3'
)




_HWHEALTH = _descriptor.Descriptor(
  name='HwHealth',
  full_name='teamspatzenhirn.HwHealth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='battery', full_name='teamspatzenhirn.HwHealth.battery', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buzzer', full_name='teamspatzenhirn.HwHealth.buzzer', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='led_status', full_name='teamspatzenhirn.HwHealth.led_status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='led_orange', full_name='teamspatzenhirn.HwHealth.led_orange', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='led_blue', full_name='teamspatzenhirn.HwHealth.led_blue', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pwm', full_name='teamspatzenhirn.HwHealth.pwm', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indicator_front', full_name='teamspatzenhirn.HwHealth.indicator_front', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indicator_rear', full_name='teamspatzenhirn.HwHealth.indicator_rear', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usb', full_name='teamspatzenhirn.HwHealth.usb', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='udp', full_name='teamspatzenhirn.HwHealth.udp', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protobuf', full_name='teamspatzenhirn.HwHealth.protobuf', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sbus', full_name='teamspatzenhirn.HwHealth.sbus', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sbus_uart', full_name='teamspatzenhirn.HwHealth.sbus_uart', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acc', full_name='teamspatzenhirn.HwHealth.acc', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro', full_name='teamspatzenhirn.HwHealth.gyro', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steering', full_name='teamspatzenhirn.HwHealth.steering', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesc_rx_front_left', full_name='teamspatzenhirn.HwHealth.vesc_rx_front_left', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesc_rx_front_right', full_name='teamspatzenhirn.HwHealth.vesc_rx_front_right', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesc_rx_rear_left', full_name='teamspatzenhirn.HwHealth.vesc_rx_rear_left', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesc_rx_rear_right', full_name='teamspatzenhirn.HwHealth.vesc_rx_rear_right', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesc_tx_front_left', full_name='teamspatzenhirn.HwHealth.vesc_tx_front_left', index=20,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesc_tx_front_right', full_name='teamspatzenhirn.HwHealth.vesc_tx_front_right', index=21,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesc_tx_rear_left', full_name='teamspatzenhirn.HwHealth.vesc_tx_rear_left', index=22,
      number=23, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesc_tx_rear_right', full_name='teamspatzenhirn.HwHealth.vesc_tx_rear_right', index=23,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=545,
)

DESCRIPTOR.message_types_by_name['HwHealth'] = _HWHEALTH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HwHealth = _reflection.GeneratedProtocolMessageType('HwHealth', (_message.Message,), {
  'DESCRIPTOR' : _HWHEALTH,
  '__module__' : 'hwhealth_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.HwHealth)
  })
_sym_db.RegisterMessage(HwHealth)


# @@protoc_insertion_point(module_scope)
