# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lights.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lights.proto',
  package='teamspatzenhirn',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0clights.proto\x12\x0fteamspatzenhirn\")\n\x18IndicatorRepetitionCount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\xb1\x01\n\x0eIndicatorState\x12\x34\n\x05state\x18\x01 \x01(\x0e\x32%.teamspatzenhirn.IndicatorState.State\x12\x38\n\x05\x63ount\x18\x02 \x01(\x0b\x32).teamspatzenhirn.IndicatorRepetitionCount\"/\n\x05State\x12\x07\n\x03OFF\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x08\n\x04\x42OTH\x10\x03\"\x1d\n\x0f\x42rakeLightState\x12\n\n\x02on\x18\x01 \x01(\x08\x62\x06proto3'
)



_INDICATORSTATE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='teamspatzenhirn.IndicatorState.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOTH', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=207,
  serialized_end=254,
)
_sym_db.RegisterEnumDescriptor(_INDICATORSTATE_STATE)


_INDICATORREPETITIONCOUNT = _descriptor.Descriptor(
  name='IndicatorRepetitionCount',
  full_name='teamspatzenhirn.IndicatorRepetitionCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='teamspatzenhirn.IndicatorRepetitionCount.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=74,
)


_INDICATORSTATE = _descriptor.Descriptor(
  name='IndicatorState',
  full_name='teamspatzenhirn.IndicatorState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='teamspatzenhirn.IndicatorState.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='teamspatzenhirn.IndicatorState.count', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INDICATORSTATE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=254,
)


_BRAKELIGHTSTATE = _descriptor.Descriptor(
  name='BrakeLightState',
  full_name='teamspatzenhirn.BrakeLightState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='on', full_name='teamspatzenhirn.BrakeLightState.on', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=285,
)

_INDICATORSTATE.fields_by_name['state'].enum_type = _INDICATORSTATE_STATE
_INDICATORSTATE.fields_by_name['count'].message_type = _INDICATORREPETITIONCOUNT
_INDICATORSTATE_STATE.containing_type = _INDICATORSTATE
DESCRIPTOR.message_types_by_name['IndicatorRepetitionCount'] = _INDICATORREPETITIONCOUNT
DESCRIPTOR.message_types_by_name['IndicatorState'] = _INDICATORSTATE
DESCRIPTOR.message_types_by_name['BrakeLightState'] = _BRAKELIGHTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IndicatorRepetitionCount = _reflection.GeneratedProtocolMessageType('IndicatorRepetitionCount', (_message.Message,), {
  'DESCRIPTOR' : _INDICATORREPETITIONCOUNT,
  '__module__' : 'lights_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.IndicatorRepetitionCount)
  })
_sym_db.RegisterMessage(IndicatorRepetitionCount)

IndicatorState = _reflection.GeneratedProtocolMessageType('IndicatorState', (_message.Message,), {
  'DESCRIPTOR' : _INDICATORSTATE,
  '__module__' : 'lights_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.IndicatorState)
  })
_sym_db.RegisterMessage(IndicatorState)

BrakeLightState = _reflection.GeneratedProtocolMessageType('BrakeLightState', (_message.Message,), {
  'DESCRIPTOR' : _BRAKELIGHTSTATE,
  '__module__' : 'lights_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.BrakeLightState)
  })
_sym_db.RegisterMessage(BrakeLightState)


# @@protoc_insertion_point(module_scope)
