# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: setpoint.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util_pb2 as util__pb2
import time_pb2 as time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='setpoint.proto',
  package='teamspatzenhirn',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esetpoint.proto\x12\x0fteamspatzenhirn\x1a\nutil.proto\x1a\ntime.proto\"\x93\x01\n\x13SingleTrackSetpoint\x12\x1a\n\x12steeringAngleFront\x18\x01 \x01(\x01\x12\x19\n\x11steeringAngleRear\x18\x02 \x01(\x01\x12\x10\n\x08velocity\x18\x03 \x01(\x01\x12\x33\n\x0fmeasurementTime\x18\x04 \x01(\x0b\x32\x1a.teamspatzenhirn.TimeStamp\"\xb8\x01\n\x0c\x46ullSetpoint\x12\x38\n\x0esteeringAngles\x18\x01 \x01(\x0b\x32 .teamspatzenhirn.FourWheelDouble\x12\x39\n\x0fwheelVelocities\x18\x02 \x01(\x0b\x32 .teamspatzenhirn.FourWheelDouble\x12\x33\n\x0fmeasurementTime\x18\x03 \x01(\x0b\x32\x1a.teamspatzenhirn.TimeStamp\"\x0e\n\x0cYeetSetpointb\x06proto3'
  ,
  dependencies=[util__pb2.DESCRIPTOR,time__pb2.DESCRIPTOR,])




_SINGLETRACKSETPOINT = _descriptor.Descriptor(
  name='SingleTrackSetpoint',
  full_name='teamspatzenhirn.SingleTrackSetpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='steeringAngleFront', full_name='teamspatzenhirn.SingleTrackSetpoint.steeringAngleFront', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steeringAngleRear', full_name='teamspatzenhirn.SingleTrackSetpoint.steeringAngleRear', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='teamspatzenhirn.SingleTrackSetpoint.velocity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurementTime', full_name='teamspatzenhirn.SingleTrackSetpoint.measurementTime', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=207,
)


_FULLSETPOINT = _descriptor.Descriptor(
  name='FullSetpoint',
  full_name='teamspatzenhirn.FullSetpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='steeringAngles', full_name='teamspatzenhirn.FullSetpoint.steeringAngles', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wheelVelocities', full_name='teamspatzenhirn.FullSetpoint.wheelVelocities', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurementTime', full_name='teamspatzenhirn.FullSetpoint.measurementTime', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=394,
)


_YEETSETPOINT = _descriptor.Descriptor(
  name='YeetSetpoint',
  full_name='teamspatzenhirn.YeetSetpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=410,
)

_SINGLETRACKSETPOINT.fields_by_name['measurementTime'].message_type = time__pb2._TIMESTAMP
_FULLSETPOINT.fields_by_name['steeringAngles'].message_type = util__pb2._FOURWHEELDOUBLE
_FULLSETPOINT.fields_by_name['wheelVelocities'].message_type = util__pb2._FOURWHEELDOUBLE
_FULLSETPOINT.fields_by_name['measurementTime'].message_type = time__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['SingleTrackSetpoint'] = _SINGLETRACKSETPOINT
DESCRIPTOR.message_types_by_name['FullSetpoint'] = _FULLSETPOINT
DESCRIPTOR.message_types_by_name['YeetSetpoint'] = _YEETSETPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SingleTrackSetpoint = _reflection.GeneratedProtocolMessageType('SingleTrackSetpoint', (_message.Message,), {
  'DESCRIPTOR' : _SINGLETRACKSETPOINT,
  '__module__' : 'setpoint_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.SingleTrackSetpoint)
  })
_sym_db.RegisterMessage(SingleTrackSetpoint)

FullSetpoint = _reflection.GeneratedProtocolMessageType('FullSetpoint', (_message.Message,), {
  'DESCRIPTOR' : _FULLSETPOINT,
  '__module__' : 'setpoint_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.FullSetpoint)
  })
_sym_db.RegisterMessage(FullSetpoint)

YeetSetpoint = _reflection.GeneratedProtocolMessageType('YeetSetpoint', (_message.Message,), {
  'DESCRIPTOR' : _YEETSETPOINT,
  '__module__' : 'setpoint_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.YeetSetpoint)
  })
_sym_db.RegisterMessage(YeetSetpoint)


# @@protoc_insertion_point(module_scope)
