# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='time.proto',
  package='teamspatzenhirn',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntime.proto\x12\x0fteamspatzenhirn\" \n\tTimeStamp\x12\x13\n\x0bnanoseconds\x18\x01 \x01(\x03\"9\n\x0fTimeSyncRequest\x12&\n\x02t0\x18\x01 \x01(\x0b\x32\x1a.teamspatzenhirn.TimeStamp\"\x87\x01\n\rTimeSyncReply\x12&\n\x02t0\x18\x01 \x01(\x0b\x32\x1a.teamspatzenhirn.TimeStamp\x12&\n\x02t1\x18\x02 \x01(\x0b\x32\x1a.teamspatzenhirn.TimeStamp\x12&\n\x02t2\x18\x03 \x01(\x0b\x32\x1a.teamspatzenhirn.TimeStampb\x06proto3'
)




_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='teamspatzenhirn.TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nanoseconds', full_name='teamspatzenhirn.TimeStamp.nanoseconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=63,
)


_TIMESYNCREQUEST = _descriptor.Descriptor(
  name='TimeSyncRequest',
  full_name='teamspatzenhirn.TimeSyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='t0', full_name='teamspatzenhirn.TimeSyncRequest.t0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=122,
)


_TIMESYNCREPLY = _descriptor.Descriptor(
  name='TimeSyncReply',
  full_name='teamspatzenhirn.TimeSyncReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='t0', full_name='teamspatzenhirn.TimeSyncReply.t0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t1', full_name='teamspatzenhirn.TimeSyncReply.t1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t2', full_name='teamspatzenhirn.TimeSyncReply.t2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=260,
)

_TIMESYNCREQUEST.fields_by_name['t0'].message_type = _TIMESTAMP
_TIMESYNCREPLY.fields_by_name['t0'].message_type = _TIMESTAMP
_TIMESYNCREPLY.fields_by_name['t1'].message_type = _TIMESTAMP
_TIMESYNCREPLY.fields_by_name['t2'].message_type = _TIMESTAMP
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['TimeSyncRequest'] = _TIMESYNCREQUEST
DESCRIPTOR.message_types_by_name['TimeSyncReply'] = _TIMESYNCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'time_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.TimeStamp)
  })
_sym_db.RegisterMessage(TimeStamp)

TimeSyncRequest = _reflection.GeneratedProtocolMessageType('TimeSyncRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMESYNCREQUEST,
  '__module__' : 'time_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.TimeSyncRequest)
  })
_sym_db.RegisterMessage(TimeSyncRequest)

TimeSyncReply = _reflection.GeneratedProtocolMessageType('TimeSyncReply', (_message.Message,), {
  'DESCRIPTOR' : _TIMESYNCREPLY,
  '__module__' : 'time_pb2'
  # @@protoc_insertion_point(class_scope:teamspatzenhirn.TimeSyncReply)
  })
_sym_db.RegisterMessage(TimeSyncReply)


# @@protoc_insertion_point(module_scope)
